name: Run Flask App on Self Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show files on runner
        run: |
          pwd
          ls -la

      - name: Build Docker image
        run: |
          docker build --network=host -t score-predictor-app .

      - name: Stop old container if it exists
        run: |
          docker stop score-predictor-container || true
          docker rm score-predictor-container || true

      - name: Run Flask app container
        run: |
          docker run -d \
            --name score-predictor-container \
            -p 5000:5000 \
            score-predictor-app

      - name: Show running containers
        run: |
          docker ps
